/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './layouts/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '2rem',
        lg: '4rem',
        xl: '5rem',
        '2xl': '6rem',
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
    },
    extend: {
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '144': '36rem',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
        display: ['Orbitron', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'xxs': ['0.625rem', { lineHeight: '0.875rem' }],
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      letterSpacing: {
        tighter: '-0.05em',
        tight: '-0.025em',
        normal: '0',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
        tech: '0.15em',
      },
      lineHeight: {
        'extra-tight': '0.75',
        'tight': '1',
        'snug': '1.25',
        'normal': '1.5',
        'relaxed': '1.75',
        'loose': '2',
      },
      borderRadius: {
        'none': '0',
        'sm': '0.125rem',
        'base': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'tech': '0.25rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-light': 'bounce 2s infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'scan': 'scan 4s linear infinite',
        'float': 'float 3s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'pulse-border': 'pulseBorder 1.5s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        glow: {
          '0%': { filter: 'brightness(1) drop-shadow(0 0 8px currentColor)' },
          '100%': { filter: 'brightness(1.2) drop-shadow(0 0 16px currentColor)' },
        },
        scan: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        pulseBorder: {
          '0%, 100%': { borderColor: 'oklch(var(--p) / 0.3)' },
          '50%': { borderColor: 'oklch(var(--p))' },
        },
      },
      boxShadow: {
        'glow-sm': '0 0 8px currentColor',
        'glow': '0 0 16px currentColor',
        'glow-lg': '0 0 24px currentColor',
        'glow-xl': '0 0 32px currentColor',
        'inner-glow': 'inset 0 0 12px currentColor',
        'tech': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'tech-lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'tech-grid': 'linear-gradient(rgba(0, 255, 65, 0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(0, 255, 65, 0.1) 1px, transparent 1px)',
        'tech-dots': 'radial-gradient(circle, rgba(0, 255, 65, 0.15) 1px, transparent 1px)',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        tromper: {
          'primary': '#00ff41',
          'primary-focus': '#00cc33',
          'primary-content': '#000000',
          
          'secondary': '#0066ff',
          'secondary-focus': '#0052cc',
          'secondary-content': '#ffffff',
          
          'accent': '#00ffff',
          'accent-focus': '#00cccc',
          'accent-content': '#000000',
          
          'neutral': '#0f0f0f',
          'neutral-focus': '#050505',
          'neutral-content': '#ffffff',
          
          'base-100': '#000000',
          'base-200': '#050505',
          'base-300': '#0a0a0a',
          'base-content': '#ffffff',
          
          'info': '#00aaff',
          'info-content': '#000000',
          'success': '#00ff41',
          'success-content': '#000000',
          'warning': '#ffaa00',
          'warning-content': '#000000',
          'error': '#ff0066',
          'error-content': '#ffffff',
          
          '--rounded-box': '0.25rem',
          '--rounded-btn': '0.25rem',
          '--rounded-badge': '0.25rem',
          '--animation-btn': '0.25s',
          '--animation-input': '0.2s',
          '--btn-text-case': 'uppercase',
          '--btn-focus-scale': '0.98',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.25rem',
          
          '--heading-font-weight': '700',
          '--body-font-weight': '400',
          '--label-font-weight': '500',
          
          '--padding-card': '1.5rem',
          '--padding-btn': '0.75rem 1.5rem',
          '--gap-default': '0.5rem',
          
          '--input-height': '3rem',
          '--navbar-height': '4rem',
          '--sidebar-width': '16rem',
          '--modal-backdrop': 'rgba(0, 0, 0, 0.8)',
          
          '--transition-fast': '150ms ease',
          '--transition-base': '200ms ease',
          '--transition-slow': '300ms ease',
          
          '--z-dropdown': '1000',
          '--z-sticky': '1020',
          '--z-fixed': '1030',
          '--z-modal-backdrop': '1040',
          '--z-modal': '1050',
          '--z-popover': '1060',
          '--z-tooltip': '1070',
        },
      },
    ],
  },
} 